version: '3.3'

services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgesql/data
    env_file: ./postgres/.env

volumes:
  db:
    driver: local
