version: '3.3'

services:
  postgresDB:
    image: postgres:14.1-alpine
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgesql/data
    env_file: ./.env

volumes:
  db:
    driver: local
